apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system
spec:
  commonName: istio-ingressgateway.istio-system.svc.local
  dnsNames:
  - istio-ingressgateway.istio-system.svc.local
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt-cluster-issuer
  secretName: istio-ingressgateway-certs
