apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubeflow-virtualservice
spec:
  hosts:
  -'*'
  gateways:
  - kubeflow/kubeflow-gateway
  http:
  - match:
    - port: 443
    - uri:
        prefix: /kubeflow
    route:
    - destination:
        port:
          number: 31709
        host: '*'
