apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: lets-encrypt-cluster-issuer
spec:
  acme:
    email: tanniru.srikanth@live.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: lets-encrypt-cluster-issuer
    solvers:
    - http01:
        ingress:
          class: istio

